# Generated by Django 2.0.3 on 2018-03-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='silvers',
            new_name='oil',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='payed',
            new_name='stat_pay',
        ),
        migrations.AddField(
            model_name='profile',
            name='stat_tower',
            field=models.IntegerField(default=0),
        ),
    ]
