# Generated by Django 2.0.3 on 2018-03-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20180320_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_referral', models.IntegerField()),
                ('id_referrer', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
