# Generated by Django 2.0.3 on 2018-03-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_delete_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название акции. Оно будет видно только вам.', max_length=64, unique=True)),
                ('description', models.TextField(help_text='Система будет отображать этот текст пользователям при пополнении счёта. HTML-коды разрешены.')),
                ('promo', models.PositiveSmallIntegerField(help_text='Бонус при пополнении в процентах')),
            ],
        ),
    ]
