# Generated by Django 2.0.3 on 2018-04-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='color',
            field=models.CharField(default='info', help_text='Выберите цвет уведомления. Доступны следующие: info (синий), warning (желтый), success (зеленый), danger (красный).', max_length=10),
        ),
    ]
