# Generated by Django 2.0.3 on 2018-03-15 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_factory_tower'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFactory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('user_id', models.IntegerField()),
                ('tower_id', models.IntegerField()),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Factory')),
            ],
        ),
        migrations.CreateModel(
            name='ClientTower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('work', models.IntegerField()),
                ('tower_name', models.CharField(max_length=256)),
                ('tower_oil', models.IntegerField()),
                ('tower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Tower')),
            ],
        ),
    ]
