# Generated by Django 2.0.3 on 2018-04-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20180406_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Support',
        ),
    ]
