# Generated by Django 2.0.3 on 2018-04-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_delete_support'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienttower',
            old_name='tower_id',
            new_name='tower',
        ),
        migrations.RemoveField(
            model_name='clientfactory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='clientfactory',
            name='tower_id',
        ),
        migrations.RemoveField(
            model_name='clienttower',
            name='tower_name',
        ),
        migrations.RemoveField(
            model_name='clienttower',
            name='tower_oil',
        ),
    ]
