# Generated by Django 2.0.3 on 2018-04-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20180414_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowerLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название уровня. Оно видно только вам.', max_length=30, unique=True)),
                ('up', models.PositiveSmallIntegerField(help_text='Количество нефти, которое получит вышка после получения уровня.')),
            ],
        ),
        migrations.AddField(
            model_name='clienttower',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
