# Generated by Django 2.0.3 on 2018-04-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20180414_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerlevel',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, help_text='Цена перехода на этот уровень'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='towerlevel',
            name='name',
            field=models.CharField(help_text='Название уровня. Отображается в таблице уровней вышек.', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='towerlevel',
            name='up',
            field=models.PositiveSmallIntegerField(help_text='Данное число всегда прибавляется к основной производительности вышки при сборе. Чем больше уровень - тем больше число.'),
        ),
    ]
