# Generated by Django 2.0.3 on 2018-04-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surfing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariff',
            old_name='oil',
            new_name='time',
        ),
    ]
