# Generated by Django 2.0.3 on 2018-04-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfing', '0002_auto_20180419_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='time',
            field=models.PositiveSmallIntegerField(help_text='Время просмотра сайта (сек.)'),
        ),
    ]
