# Generated by Django 2.0.3 on 2018-04-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfing', '0003_auto_20180419_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='name',
            field=models.CharField(default='Standart', help_text='Название тарифа', max_length=50),
            preserve_default=False,
        ),
    ]
