# Generated by Django 2.0.3 on 2018-04-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfing', '0004_tariff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfingsite',
            name='url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
    ]
