# Generated by Django 2.0.3 on 2018-04-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfing', '0005_surfingsite_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfingsite',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
