# Generated by Django 2.0.3 on 2018-04-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_auto_20180412_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalmessage',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
